# Generated by Django 5.0 on 2023-12-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forgotOtp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isVerified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='loginOtp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referralId',
        ),
    ]
