# Generated by Django 5.0 on 2023-12-30 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0002_remove_user_forgototp_remove_user_isverified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseType', models.SmallIntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distributed_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_user_ref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='ExpensesDistributedBetweenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distributed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_ref', to='RestAPI.expenses')),
            ],
            options={
                'db_table': 'ExpensesDistributed',
            },
        ),
    ]
