# Generated by Django 5.0 on 2023-12-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_expenses_expensesdistributedbetweenuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expenseType',
            field=models.SmallIntegerField(),
        ),
    ]
